- src/app/material/material.module.ts
- src/app/mini-games/mini-games-routing.module.ts
- src/app/mini-games/mini-games.module.ts
- src/app/mini-games/pages/mini-games-page/mini-games-page.component.html
- src/app/mini-games/pages/mini-games-page/mini-games-page.component.scss
- src/app/mini-games/pages/mini-games-page/mini-games-page.component.spec.ts
- src/app/mini-games/pages/mini-games-page/mini-games-page.component.ts
- src/app/mini-games/sprint/sprint-mini-game.component.html
- src/app/mini-games/sprint/sprint-mini-game.component.spec.ts
- src/app/mini-games/sprint/sprint-mini-game.component.ts
1) add mini-games page (mini-games/):
2) add mini-games routing:
mini-games/sprint
mini-games/audiochallenge
mini-games/savannah
mini-games/custom-game
> feat: add mini-games page & mini-games routing

- src/app/constants/constants.ts
- src/app/services/mini-game-words.service.spec.ts
- src/app/services/mini-games-http.service.ts
Add http service for mini-games:
- getWords(): sends request for 20 default words;
- getWordById(id: string):  send request for 1 word with assets
Add constants file with one constant - api url
> feat: add mini-games http service

- src/app/mini-games/custom-mini-game/custom-mini-game.component.html
- src/app/mini-games/custom-mini-game/custom-mini-game.component.ts
- src/app/mini-games/custom-mini-game/services/sound.service.ts
- src/app/mini-games/custom-mini-game/start-dialog/start-dialog.component.html
- src/app/mini-games/custom-mini-game/start-dialog/start-dialog.component.scss
- src/app/mini-games/custom-mini-game/start-dialog/start-dialog.component.spec.ts
- src/app/mini-games/custom-mini-game/start-dialog/start-dialog.component.ts
- src/app/mini-games/mini-games.module.ts
Task: Custom Game
Добавлен стартовый диалог с настройками + выходной диалог с выводом статистики за игру (общий компонент для мини-игр)
Date: 02.04.2021
> feat: #15 add setup start dialog and end game dialog

- src/app/core/constants/statistics.ts
- src/app/core/models/ILongTermStats.ts
- src/app/core/models/IShortTermStats.ts
- src/app/core/services/statistics.service.ts
- src/app/mini-games/shared/components/close-game-dialog/close-game-dialog.component.scss
- src/app/mini-games/shared/components/end-game/end-game.component.html
- src/app/mini-games/shared/components/end-game/end-game.component.scss
- src/app/mini-games/shared/components/end-game/end-game.component.ts
- src/app/mini-games/sprint/sprint-mini-game.component.html
- src/app/mini-games/sprint/sprint-mini-game.component.scss
- src/app/mini-games/sprint/sprint-mini-game.component.ts
- src/app/statistics/components/long-term-statistics/long-term-statistics/long-term-statistics.component.html
- src/app/statistics/components/long-term-statistics/long-term-statistics/long-term-statistics.component.scss
- src/app/statistics/components/long-term-statistics/long-term-statistics/long-term-statistics.component.ts
- src/app/statistics/components/short-term-statistics/short-term-statistics/short-term-statistics.component.html
- src/app/statistics/components/short-term-statistics/short-term-statistics/short-term-statistics.component.scss
- src/app/statistics/components/short-term-statistics/short-term-statistics/short-term-statistics.component.ts
- src/app/statistics/pages/statistics-page/statistics-page.component.ts
- src/app/statistics/services/long-term-statistics/long-term-statistics.service.ts
- src/app/statistics/services/short-term-statistics/short-term-statistics.service.ts
* add long-term statistics
* corrections of short-term statistics
> feat: add long-term statistics

- src/app/auth/const/patterns.ts
- src/app/auth/pages/login/login.component.ts
- src/app/auth/pages/signup/signup.component.ts
- src/app/mini-games/savannah/pages/savannah-mini-game/savannah-mini-game.component.html
- src/app/mini-games/shared/components/start-game/start-game.component.html
- src/app/mini-games/shared/components/start-game/start-game.component.scss
- src/app/mini-games/shared/components/start-game/start-game.component.ts
- src/app/mini-games/sprint/sprint-mini-game.component.html
* regexp validation fix
* start-game component refactor
> fix: regexp validation + start-game component

- src/app/mini-games/audiochallenge/components/audiochallenge-main/audiochallenge-main.component.scss
- src/app/mini-games/custom-mini-game/custom-mini-game.component.html
- src/app/mini-games/custom-mini-game/custom-mini-game.component.scss
- src/app/mini-games/custom-mini-game/custom-mini-game.component.ts
- src/app/mini-games/pages/mini-games-page/mini-games-page.component.scss
- src/app/mini-games/savannah/pages/savannah-mini-game/savannah-mini-game.component.html
- src/app/mini-games/savannah/pages/savannah-mini-game/savannah-mini-game.component.scss
- src/app/mini-games/shared/components/close-game-dialog/close-game-dialog.component.html
- src/app/mini-games/shared/components/close-game-dialog/close-game-dialog.component.scss
- src/app/mini-games/shared/components/counter/counter.component.scss
- src/app/mini-games/shared/components/start-game/start-game.component.ts
- src/app/mini-games/sprint/sprint-mini-game.component.scss
- src/app/statistics/pages/statistics-page/statistics-page.component.scss
* mini-games styles corrections
* custom game change start & exit components to shared
> refactor: game styles

- src/app/textbook/components/textbook-mini-games/textbook-mini-games.component.html
- src/app/textbook/components/textbook-mini-games/textbook-mini-games.component.scss
Changed styles for game links in textbook page.
> feat: add styles in text book

- src/app/core/models/IAnswer.ts
- src/app/core/models/ISavannahGame.ts
- src/app/core/models/ISprintGame.ts
- src/app/core/models/ITrainedWord.ts
- src/app/mini-games/custom-mini-game/custom-mini-game.component.ts
- src/app/mini-games/savannah/components/options-input/options-input.component.spec.ts
- src/app/mini-games/savannah/components/options-input/options-input.component.ts
- src/app/mini-games/savannah/pages/savannah-mini-game/savannah-mini-game.component.ts
- src/app/mini-games/savannah/services/savannah.service.ts
- src/app/mini-games/shared/components/end-game/end-game.component.spec.ts
- src/app/mini-games/shared/components/end-game/end-game.component.ts
- src/app/mini-games/sprint/components/sprint-game-card/sprint-game-card.component.ts
- src/app/mini-games/sprint/sprint-mini-game.component.ts
- src/app/redux/reducers/audiochallengeReducer.ts
- src/app/statistics/components/short-term-statistics/short-term-statistics/short-term-statistics.component.ts
- src/app/textbook/components/textbook-menu/textbook-menu.component.spec.ts
fix savannah errors occurred after moving logic to service, move Answer model outside of  ISprint model
> fix: fixes in savannah 

- src/app/core/models/ITrainedWord.ts
- src/app/core/models/IWord.ts
- src/app/mini-games/custom-mini-game/custom-mini-game.component.ts
- src/app/mini-games/savannah/pages/savannah-mini-game/savannah-mini-game.component.ts
- src/app/mini-games/savannah/services/savannah.service.ts
- src/app/mini-games/shared/components/end-game/end-game.component.ts
- src/app/mini-games/sprint/sprint-mini-game.component.html
- src/app/mini-games/sprint/sprint-mini-game.component.ts
- src/app/redux/actions/textbooks.actions.ts
- src/app/redux/effects/textbook.effect.ts
- src/app/redux/selectors/user.selector.ts
- src/app/services/mini-games-http.service.ts
- src/app/textbook/components/dictionary-content/dictionary-content.component.ts
- src/app/textbook/components/textbook-content/textbook-content.component.ts
- src/app/textbook/components/word-card/word-card.component.ts
Custom mini-game:
- get words from textbook and add words to dictionary.
Update: All mini-games get right words and add words to dictionary.
> feat: custom game correct words and results

- src/app/textbook/components/dictionary-content/dictionary-content.component.html
- src/app/textbook/components/dictionary-content/dictionary-content.component.scss
- src/app/textbook/components/textbook-content/textbook-content.component.html
- src/app/textbook/components/textbook-content/textbook-content.component.scss
- src/app/textbook/components/textbook-statistic/textbook-statistic.component.html
- src/app/textbook/components/textbook-statistic/textbook-statistic.component.scss
- src/app/textbook/components/textbook-statistic/textbook-statistic.component.spec.ts
- src/app/textbook/components/textbook-statistic/textbook-statistic.component.ts
- src/app/textbook/components/word-card/word-card.component.html
- src/app/textbook/components/word-card/word-card.component.scss
- src/app/textbook/components/word-card/word-card.component.ts
- src/app/textbook/textbook.module.ts
Add statistic count in textbook and dictionary.
> feat: add statistic count in textbook and dictionary

- src/app/mini-games/custom-mini-game/custom-mini-game.component.html
- src/app/mini-games/custom-mini-game/custom-mini-game.component.ts
Task: #15 Custom game
Включен переход на стартовый экран с настройками при перезапуске игры с экрана результатов игры
Исправлена проблема включением/ выключением звука при перезапуске игры
Date: 08.04.2021
> refactor: fix restart game flow and toggle sound issues

- src/app/core/constants/common.ts
- src/app/core/constants/statistics.ts
- src/app/core/models/ILongTermStats.ts
- src/app/mini-games/audiochallenge/components/audiochallenge-main/audiochallenge-main.component.html
- src/app/mini-games/audiochallenge/components/audiochallenge-main/audiochallenge-main.component.ts
- src/app/mini-games/custom-mini-game/custom-mini-game.component.html
- src/app/mini-games/custom-mini-game/custom-mini-game.component.ts
- src/app/mini-games/savannah/pages/savannah-mini-game/savannah-mini-game.component.html
- src/app/mini-games/savannah/pages/savannah-mini-game/savannah-mini-game.component.ts
- src/app/mini-games/savannah/services/savannah.service.ts
- src/app/mini-games/shared/components/end-game/end-game.component.ts
- src/app/mini-games/sprint/sprint-mini-game.component.html
- src/app/mini-games/sprint/sprint-mini-game.component.ts
- src/app/statistics/components/short-term-statistics/short-term-statistics/short-term-statistics.component.html
- src/app/statistics/services/long-term-statistics/long-term-statistics.service.ts
* add in LongTermStatisticsService method getStatisticsByGroups() which return Observable<ILongTermStatsByGroups> [wordGroup: string]: {
learnedWords: Set of words ids;
correctAnswers: number;
wrongAnswers: number;
};
* some statistics corrections
> refactor: statistics corrections

- src/app/mini-games/shared/components/end-game/end-game.component.ts
- src/app/statistics/components/long-term-statistics/long-term-statistics/long-term-statistics.component.ts
- src/app/statistics/services/long-term-statistics/long-term-statistics.service.ts
long-term stats initial settings fix - if there are no stats on the server for the user and error with statusText = "Not Found" returned, initial stats are set.
> fix: long-term stats initial settings

- src/app/main/pages/home-page/home-page.component.scss
- src/app/redux/reducers/textbookReducer.ts
- src/app/textbook/components/textbook-statistic/textbook-statistic.component.scss
- src/app/textbook/components/word-card/word-card.component.ts
Add loader on button event and fix tooltip.
> feat: add loader on button event

- src/app/statistics/components/short-term-statistics/short-term-statistics/short-term-statistics.component.html
- src/app/statistics/components/short-term-statistics/short-term-statistics/short-term-statistics.component.scss
- src/app/statistics/components/short-term-statistics/short-term-statistics/short-term-statistics.component.ts
- src/app/statistics/pages/statistics-page/statistics-page.component.scss
> updated short statistics page

- src/styles.scss
Возвращаем константы в :root для первоначальной загрузки до переключения тем
> fix: bring back constants in root

- src/app/mini-games/custom-mini-game/custom-mini-game.component.html
- src/app/mini-games/custom-mini-game/custom-mini-game.component.scss
- src/styles.scss
Дублирующие определения констант для light theme в styles.scss добавил в mixin
> refactor: move light theme vars to mixin

- src/app/auth/pages/login/login.component.html
- src/app/auth/pages/login/login.component.scss
- src/app/auth/pages/signup/signup.component.html
- src/app/auth/pages/signup/signup.component.scss
- src/app/main/pages/home-page/home-page.component.html
- src/app/main/pages/home-page/home-page.component.scss
- src/app/shared/components/file-input/file-input.component.html
- src/app/shared/components/file-input/file-input.component.scss
- src/app/textbook/components/dictionary-content/dictionary-content.component.html
- src/app/textbook/components/dictionary-content/dictionary-content.component.scss
- src/app/textbook/components/textbook-content/textbook-content.component.html
- src/app/textbook/components/textbook-content/textbook-content.component.scss
- src/app/textbook/components/textbook-statistic/textbook-statistic.component.html
- src/app/textbook/components/textbook-statistic/textbook-statistic.component.scss
- src/styles.scss
Добавление стиля переключения цвета текста для темной темы в словаре, учебнике, странице логина и регистрации
> fix: fix styles for dark theme in login signup textbook dict

- src/app/core/components/header/header.component.scss
- src/app/statistics/pages/statistics-page/statistics-page.component.scss
Delete horizontal scroll on statistic page.
> fix: statistic styles (min-height)

- src/app/auth/pages/login/login.component.scss
- src/app/auth/pages/signup/signup.component.scss
- src/app/core/constants/sprint-game.ts
- src/app/mini-games/audiochallenge/components/audiochallenge-game/audiochallenge-game.component.ts
- src/app/mini-games/audiochallenge/components/audiochallenge-main/audiochallenge-main.component.html
- src/app/mini-games/audiochallenge/components/game-sounds-button/game-sounds-button.component.html
- src/app/mini-games/audiochallenge/components/game-sounds-button/game-sounds-button.component.ts
- src/app/mini-games/audiochallenge/components/level-choise/level-choise.component.html
- src/app/mini-games/audiochallenge/components/word-card/word-card.component.html
- src/app/mini-games/custom-mini-game/custom-mini-game.component.html
- src/app/mini-games/savannah/pages/savannah-mini-game/savannah-mini-game.component.html
- src/app/mini-games/shared/components/end-game/end-game.component.html
- src/app/mini-games/spelling/components/game-sounds-button/game-sounds-button.component.ts
- src/app/mini-games/spelling/components/spelling-game/spelling-game.component.ts
- src/app/mini-games/sprint/components/sprint-game-card/sprint-game-card.component.scss
- src/app/mini-games/sprint/sprint-mini-game.component.scss
- src/app/mini-games/sprint/sprint-mini-game.component.ts
* mini-games corrections for dark theme
* spelling, audiochallenge games audio settings from service
> styles: mini-games dark theme fixes
